language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t brooksbenson03/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brooksbenson03/react-test npm test

after_success:
  - docker build -t brooksbenson03/multi-client ./client
  - docker build -t brooksbenson03/multi-nginx ./nginx
  - docker build -t brooksbenson03/multi-server ./server
  - docker build -t brooksbenson03/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push brooksbenson03/multi-client
  - docker push brooksbenson03/multi-nginx
  - docker push brooksbenson03/multi-server
  - docker push brooksbenson03/multi-worker

deploy:
  region: us-west-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-west-1-374408092827
  bucket_path: docker-multi
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: main
